---
# tasks file for motd1

- name: Set motd messages
  copy:
    content: "{{ messages.message1 }}"
    dest: /etc/motd
    owner: root
    group: root
  tags:
    - motd1  

- name: Set another message
  lineinfile:
    path: /etc/motd
    line: "{{ messages.message2 }}"
    insertafter: EOF
    owner: root
    group: root
  tags:
    - motd1  
